"""add perex to article

Revision ID: 9e690561dae3
Revises: ec5ff6c1fd0d
Create Date: 2025-11-17 21:01:51.679400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e690561dae3'
down_revision = 'ec5ff6c1fd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perex', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('perex')

    # ### end Alembic commands ###
