"""init

Revision ID: ec5ff6c1fd0d
Revises: 
Create Date: 2025-11-01 21:11:04.526600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5ff6c1fd0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('band', sa.String(length=120), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_slug'), ['slug'], unique=True)

    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('styles', sa.String(length=200), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_band_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_band_is_approved'), ['is_approved'], unique=False)

    op.create_table('gig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('venue', sa.String(length=120), nullable=True),
    sa.Column('lineup', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gig_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gig_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gig_date'))
        batch_op.drop_index(batch_op.f('ix_gig_created_at'))

    op.drop_table('gig')
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_band_is_approved'))
        batch_op.drop_index(batch_op.f('ix_band_created_at'))

    op.drop_table('band')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_slug'))
        batch_op.drop_index(batch_op.f('ix_article_published_at'))

    op.drop_table('article')
    # ### end Alembic commands ###
